import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CreatorCourseSection } from "@/components/CreatorCourseSection";
import { CreatorPromptExample } from "@/components/CreatorPromptExample";
import { yuniAiImageBasicsCourse as course } from "@/data/creator-courses";
import { publicAssetPath } from "@/lib/paths";

export const metadata: Metadata = {
  title: "YUNI AI 生圖基礎 | Creator Academy",
  description: "從角色一致性、Prompt 五大元素、場景控制到攝影語言，完成第一張具有創作意圖的 AI 圖像。",
};

export default function YuniAiImageBasicsPage() {
  const [basics, character] = course.chapters;
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14">
    <nav aria-label="課程導覽" className="flex flex-wrap items-center gap-2 text-sm text-slate-400"><Link href="/creator-academy" className="rounded-full px-2 py-2 text-cyan-100 transition hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-200">Creator Academy</Link><span aria-hidden="true">/</span><span>AI 視覺創作</span></nav>

    <header className="relative mt-6 overflow-hidden rounded-[2rem] border border-violet-300/20 bg-[radial-gradient(circle_at_75%_15%,rgba(124,58,237,0.32),transparent_35%),linear-gradient(145deg,rgba(5,21,49,0.98),rgba(10,8,37,0.94))] shadow-[0_30px_100px_rgba(2,6,23,0.4)]">
      <div className="grid lg:grid-cols-[1.08fr_0.92fr]">
        <div className="relative z-10 p-6 sm:p-10 lg:p-12"><div className="flex flex-wrap gap-2 text-[10px] font-bold tracking-[0.14em]"><span className="rounded-full border border-cyan-200/30 bg-cyan-300/10 px-3 py-1.5 text-cyan-100">FREE COURSE</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-slate-300">{course.level}</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-slate-300">{course.duration}</span></div><p className="eyebrow mt-7">{course.englishTitle}</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-white sm:text-6xl">{course.title}</h1><p className="mt-5 max-w-2xl text-base font-semibold leading-7 text-cyan-100 sm:text-lg">{course.subtitle}</p><a href="#ai-image-basics" className="mt-8 inline-flex min-h-12 items-center justify-center rounded-full border border-cyan-200/40 bg-cyan-300/15 px-6 py-3 text-sm font-bold text-cyan-50 transition hover:bg-cyan-300 hover:text-slate-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-200">開始學習 ↓</a></div>
        <div className="relative min-h-72 overflow-hidden border-t border-white/10 lg:min-h-full lg:border-l lg:border-t-0"><Image src={publicAssetPath(course.heroImage)} alt={course.heroImageAlt} fill priority sizes="(max-width: 1024px) 100vw, 45vw" unoptimized className="object-cover opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-violet-950/20 lg:bg-gradient-to-r" /><div className="absolute bottom-5 left-5 rounded-2xl border border-white/15 bg-slate-950/65 px-4 py-3 backdrop-blur-xl"><p className="text-[10px] font-bold tracking-[0.16em] text-cyan-200">YUNI VISUAL</p><p className="mt-1 text-sm text-slate-300">正式角色課程圖預留位置</p></div></div>
      </div>
    </header>

    <nav aria-label="課程章節" className="sticky top-3 z-20 mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-slate-950/80 p-2 text-xs font-semibold text-slate-300 shadow-xl backdrop-blur-xl"><a href="#ai-image-basics" className="shrink-0 rounded-xl px-3 py-2 hover:bg-white/10">基礎概念</a><a href="#yuni-character" className="shrink-0 rounded-xl px-3 py-2 hover:bg-white/10">角色設定</a><a href="#prompt-elements" className="shrink-0 rounded-xl px-3 py-2 hover:bg-white/10">Prompt</a><a href="#scene-control" className="shrink-0 rounded-xl px-3 py-2 hover:bg-white/10">場景</a><a href="#camera-language" className="shrink-0 rounded-xl px-3 py-2 hover:bg-white/10">攝影語言</a><a href="#practice" className="shrink-0 rounded-xl px-3 py-2 hover:bg-white/10">實戰</a></nav>

    <CreatorCourseSection id={basics.id} number={basics.number} eyebrow="Foundation" title={basics.title} description={basics.summary}><div className="grid gap-4 md:grid-cols-3">{basics.points.map((point) => <div key={point} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 text-sm leading-7 text-slate-300">{point}</div>)}</div></CreatorCourseSection>
    <CreatorCourseSection id={character.id} number={character.number} eyebrow="Character consistency" title={character.title} description={character.summary}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{character.points.map((point) => { const [label, detail] = point.split("："); return <div key={point} className="rounded-2xl border border-violet-300/15 bg-violet-300/[0.045] p-5"><h3 className="font-semibold text-violet-100">{label}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{detail}</p></div>; })}</div></CreatorCourseSection>
    <CreatorCourseSection id="prompt-elements" number="03" eyebrow="Prompt framework" title="Prompt 五大元素" description="把 Prompt 拆成五個可控制區塊。先固定 Subject 與 Appearance，再依作品需求替換環境、光線與鏡頭。"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{course.promptElements.map((element) => <article key={element.id} className="rounded-2xl border border-cyan-200/15 bg-cyan-300/[0.035] p-5"><span className="text-xs font-black text-cyan-300/50">{element.label}</span><h3 className="mt-4 text-lg font-semibold text-white">{element.title}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{element.description}</p></article>)}</div></CreatorCourseSection>
    <CreatorCourseSection id="scene-control" number="04" eyebrow="Environment control" title="場景控制" description="場景不是單一地點名稱；材質、時間、天氣、背景物件與人物行為都會改變作品氣氛。"><div className="grid gap-4 sm:grid-cols-2">{course.scenes.map((scene) => <article key={scene.title} className="group rounded-2xl border border-white/10 bg-gradient-to-br from-white/[0.05] to-transparent p-6 transition hover:border-cyan-200/30"><p className="text-[10px] font-bold tracking-[0.16em] text-cyan-200/65">SCENE</p><h3 className="mt-3 text-xl font-semibold text-white">{scene.title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{scene.description}</p></article>)}</div></CreatorCourseSection>
    <CreatorCourseSection id="camera-language" number="05" eyebrow="Photography language" title="攝影語言" description="用攝影術語告訴模型觀看人物的方式，讓構圖不只正確，也具有明確視覺意圖。"><div className="grid gap-4 md:grid-cols-2">{course.photographyLanguage.map((item) => <article key={item.term} className="rounded-2xl border border-amber-300/15 bg-amber-300/[0.035] p-6"><h3 className="font-mono text-lg font-semibold text-amber-100">{item.term}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{item.description}</p></article>)}</div></CreatorCourseSection>
    <CreatorCourseSection id="practice" number="06" eyebrow="YUNI case study" title="實戰案例" description="以一張室內生活照示範，觀察五大 Prompt 元素如何共同建立角色、場景與攝影感。"><CreatorPromptExample example={course.examples[0]} /></CreatorCourseSection>

    <section aria-labelledby="pro-preview" className="mb-8 overflow-hidden rounded-3xl border border-amber-300/20 bg-[radial-gradient(circle_at_85%_20%,rgba(251,191,36,0.12),transparent_35%),rgba(255,255,255,0.03)] p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold tracking-[0.18em] text-amber-200">PRO SECTION / PREVIEW</p><h2 id="pro-preview" className="mt-3 text-2xl font-semibold text-white">Creator Pass 會員解鎖</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">進階角色參考圖工作流、批次 Prompt 變體與完整商業案例將收錄於未來 Creator Pass。本階段僅保留產品概念，不建立登入或付款。</p></div><span className="inline-flex min-h-12 shrink-0 cursor-not-allowed items-center justify-center rounded-full border border-amber-300/25 bg-amber-300/10 px-5 text-sm font-bold text-amber-100" aria-disabled="true">🔒 尚未開放</span></div></section>
  </main>;
}
