[CmdletBinding()]
param([switch]$DryRun, [switch]$TestInvalidMoi)
$ErrorActionPreference = 'Stop'
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$LogsDirectory = Join-Path $ProjectRoot 'data\market-radar\logs'
$ProcessedDirectory = Join-Path $ProjectRoot 'data\market-radar\processed'
$LivePath = Join-Path $ProjectRoot 'public\data\market-radar\live\moi-real-price-latest.json'
$LastRunPath = Join-Path $ProcessedDirectory 'moi-last-run.json'
$CyclePath = Join-Path $PSScriptRoot 'run-moi-latest-cycle.mjs'
$RunnerPath = Join-Path $PSScriptRoot 'run-update-job.mjs'
New-Item -ItemType Directory -Force -Path $LogsDirectory, $ProcessedDirectory | Out-Null
$startedAt = (Get-Date).ToUniversalTime().ToString('o'); $logPath = Join-Path $LogsDirectory ("moi-latest-{0}.log" -f (Get-Date -Format 'yyyy-MM-dd'))
function Finish([hashtable]$value, [int]$exitCode) { $value.finishedAt=(Get-Date).ToUniversalTime().ToString('o'); $value.durationMs=[int](([DateTime]::Parse($value.finishedAt)-[DateTime]::Parse($value.startedAt)).TotalMilliseconds); $safe=[ordered]@{startedAt=$value.startedAt;finishedAt=$value.finishedAt;jobId='moi-latest-refresh';status=$value.status;currentPeriod=$value.currentPeriod;candidatePeriod=$value.candidatePeriod;published=$value.published;qualityPassed=$value.qualityPassed;safeMessage=$value.safeMessage;durationMs=$value.durationMs;dryRun=$value.dryRun}; ($safe|ConvertTo-Json -Compress)|Add-Content -LiteralPath $logPath -Encoding utf8; $safe|ConvertTo-Json|Set-Content -LiteralPath $LastRunPath -Encoding utf8; $value|ConvertTo-Json -Depth 8; exit $exitCode }
if (-not (Get-Command node -ErrorAction SilentlyContinue) -or -not (Get-Command npm -ErrorAction SilentlyContinue)) { Finish @{startedAt=$startedAt;status='failed';currentPeriod=$null;candidatePeriod=$null;published=$false;qualityPassed=$false;safeMessage='Node.js runtime unavailable';dryRun=[bool]$DryRun} 1 }
if ([string]::IsNullOrWhiteSpace($env:NODE_OPTIONS)) { $env:NODE_OPTIONS='--use-system-ca' }
Push-Location $ProjectRoot
try {
  $before=(Get-FileHash -LiteralPath $LivePath -Algorithm SHA256).Hash.ToLowerInvariant()
  if ($TestInvalidMoi) { $raw=& node $RunnerPath 'moi-latest-refresh' '--publish' '--candidate' (Join-Path $ProcessedDirectory 'invalid-moi-candidate.json') '--trigger' 'manual' 2>&1 }
  elseif ($DryRun) { $raw=& node $CyclePath '--trigger' 'manual' 2>&1 }
  else { $raw=& node $CyclePath '--publish' '--trigger' 'scheduled' 2>&1 }
  $nodeExit=$LASTEXITCODE; $text=($raw|Out-String).Trim(); try { $parsed=$text|ConvertFrom-Json } catch { Finish @{startedAt=$startedAt;status='failed';currentPeriod=$null;candidatePeriod=$null;published=$false;qualityPassed=$false;safeMessage='MOI runner did not return structured JSON';dryRun=[bool]$DryRun} 1 }
  $job=if($parsed.job){$parsed.job}else{$parsed}; $status=[string]$job.status; $current=if($parsed.currentPeriod){"$($parsed.currentPeriod.start) to $($parsed.currentPeriod.end)"}else{$null}; $candidate=if($parsed.candidatePeriod){"$($parsed.candidatePeriod.start) to $($parsed.candidatePeriod.end)"}elseif($job.candidateDataPeriod){"$($job.candidateDataPeriod.start) to $($job.candidateDataPeriod.end)"}else{$null}; $after=(Get-FileHash -LiteralPath $LivePath -Algorithm SHA256).Hash.ToLowerInvariant()
  if($status -eq 'skipped' -and $before -ne $after){ Finish @{startedAt=$startedAt;status='failed';currentPeriod=$current;candidatePeriod=$candidate;published=$false;qualityPassed=$false;safeMessage='SKIPPED result changed MOI LIVE unexpectedly';dryRun=[bool]$DryRun} 1 }
  if($status -eq 'published' -and -not $DryRun){ npm.cmd run typecheck; if($LASTEXITCODE -ne 0){ & node (Join-Path $PSScriptRoot 'rollback-moi-live.mjs'); Finish @{startedAt=$startedAt;status='failed';currentPeriod=$current;candidatePeriod=$candidate;published=$false;qualityPassed=$false;safeMessage='Post-publish validation failed; known-good MOI LIVE was restored.';dryRun=$false} 1 }; npm.cmd run lint; if($LASTEXITCODE -ne 0){ & node (Join-Path $PSScriptRoot 'rollback-moi-live.mjs'); Finish @{startedAt=$startedAt;status='failed';currentPeriod=$current;candidatePeriod=$candidate;published=$false;qualityPassed=$false;safeMessage='Post-publish validation failed; known-good MOI LIVE was restored.';dryRun=$false} 1 }; npm.cmd test; if($LASTEXITCODE -ne 0){ & node (Join-Path $PSScriptRoot 'rollback-moi-live.mjs'); Finish @{startedAt=$startedAt;status='failed';currentPeriod=$current;candidatePeriod=$candidate;published=$false;qualityPassed=$false;safeMessage='Post-publish validation failed; known-good MOI LIVE was restored.';dryRun=$false} 1 }; npm.cmd run build; if($LASTEXITCODE -ne 0){ & node (Join-Path $PSScriptRoot 'rollback-moi-live.mjs'); Finish @{startedAt=$startedAt;status='failed';currentPeriod=$current;candidatePeriod=$candidate;published=$false;qualityPassed=$false;safeMessage='Post-publish validation failed; known-good MOI LIVE was restored.';dryRun=$false} 1 } }
  $safe=if($status -eq 'skipped'){'No newer official MOI Kaohsiung sale batch detected; existing MOI LIVE data was retained.'}elseif($status -eq 'published'){'MOI candidate was published locally; manual deployment review remains required.'}else{'MOI latest refresh failed safely; existing LIVE data was preserved.'}; $code=if($status -in @('skipped','published','staged') -and $nodeExit -eq 0){0}else{1}; Finish @{startedAt=$startedAt;status=$status;currentPeriod=$current;candidatePeriod=$candidate;published=[bool]$job.published;qualityPassed=if($status -eq 'skipped'){$true}else{[bool]$job.qualityPassed};safeMessage=$safe;dryRun=[bool]$DryRun;moiLiveSha256Before=$before;moiLiveSha256After=$after} $code
} finally { Pop-Location }
