import Link from "next/link";
import { CreatorStudioHero } from "@/components/CreatorStudioHero";
import { LearningAppCard } from "@/components/LearningAppCard";
import { learningApps } from "@/data/learning-apps";
import { categories } from "@/data/site";

export default function Home() {
  return <div className="home-page">
    <CreatorStudioHero />
    <div className="mx-auto max-w-6xl px-5 pb-2 sm:px-8">
    <section aria-labelledby="learning-apps" className="home-learning-section"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Interactive tools</p><h2 id="learning-apps" className="mt-2 text-3xl font-semibold text-white">Learning Apps</h2><p className="mt-2 text-sm text-slate-300">從一個互動入口，立刻開始練習與探索。</p></div><span className="rounded-full border border-cyan-300/20 bg-cyan-300/5 px-3 py-1.5 text-xs text-cyan-100">OPEN IN NEW TAB</span></div><div className="grid gap-4 lg:grid-cols-3">{learningApps.map((app) => <LearningAppCard app={app} key={app.id} />)}</div></section>
    <section aria-labelledby="categories" className="mt-20"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow text-cyan-200/75">More to explore</p><h2 id="categories" className="mt-2 text-2xl font-semibold">探索分類</h2></div><span className="text-xs text-slate-500">07 COLLECTIONS</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map((item) => <Link href={item.href} key={item.href} className="glass group cursor-pointer rounded-2xl p-5 transition hover:-translate-y-1 hover:border-cyan-200/40 hover:bg-slate-800/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-200"><span className="text-xs font-bold tracking-widest text-cyan-300">{item.label}</span><h3 className="mt-7 text-xl font-semibold text-white">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{item.description}</p><span className="mt-5 block text-xs text-cyan-200 opacity-0 transition group-hover:opacity-100 group-focus-visible:opacity-100">進入分類 →</span></Link>)}</div></section>
    <section className="mt-16 grid gap-4 lg:grid-cols-2"><div className="glass rounded-2xl p-6"><p className="eyebrow">Latest tutorial</p><h2 className="mt-3 text-2xl font-semibold">Seedance 2.0｜真人 × 動漫分身房屋介紹</h2><p className="mt-3 text-sm leading-6 text-slate-300">完整英文 Prompt、5 段分鏡與可下載 PDF 的 AI 影音教學。</p><Link href="/ai-tutorials/seedance-2-real-anime-home-tour" className="mt-5 inline-block cursor-pointer text-sm font-semibold text-cyan-300 transition hover:text-cyan-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-200">閱讀教學 →</Link></div><div className="glass rounded-2xl p-6"><p className="eyebrow">Popular resources</p><h2 className="mt-3 text-2xl font-semibold">免費資源庫</h2><p className="mt-3 text-sm leading-6 text-slate-300">精選工具、模板與下載素材，將逐步開放。</p><Link href="/resources" className="mt-5 inline-block cursor-pointer text-sm font-semibold text-cyan-300 transition hover:text-cyan-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-200">查看資源 →</Link></div></section>
    </div>
  </div>;
}
